name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus
        run: npm run build  # <-- Quan trọng: tạo thư mục build/

      - name: Copy build files
        run: cp -r build/* ./  # Bây giờ build/ tồn tại

      - name: Deploy (ví dụ: dùng rsync, scp, hoặc Vercel)
        # ... tiếp tục deploy