name: Deploy Docusaurus

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: |
          yarn build
          ls -la
          if [ -d "build" ]; then
            ls -la build
          else
            echo "❌ Build failed: no build folder"
            exit 1
          fi

      - name: Prepare deploy folder
        run: |
          find . -maxdepth 1 ! -name ".github" ! -name "README.md" ! -name "." ! -name ".." -exec rm -rf {} +
          cp -r build/* ./
          touch .nojekyll  # Tắt Jekyll nếu cần

      - name: Deploy to main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy Docusaurus site" || echo "No changes"
          git push origin main